### ISSUE TITLE
GDG- MyVITChrome | Credit Problems

### ISSUE THREAD

**Issue by r00tdaemon** [rahulkapoor90/VITacademics-Enhancement-Suite#36]
You guys have simply copied the designs of [MyVIT Chrome Extension](https://github.com/GDGVIT/MyVIT-chrome) 

This is MyVIT extension
![screenshot from 2017-05-09 17-25-47](https://cloud.githubusercontent.com/assets/16747982/25849624/d2e1815c-34dc-11e7-97fb-ea0726642c8f.png)

And this is VES
![screenshot from 2017-05-09 17-25-44](https://cloud.githubusercontent.com/assets/16747982/25849616/ca874974-34dc-11e7-996e-93d536102e40.png)

Can't even copy correctly? The bar representing theory attendance is of different color.
We refused to merge the project with yours doesn't mean that you can simply copy it without giving the credits where due and shamelessly promote it as something which you made.
Shows what kind of developers you and your team are.

**Comment by aalind0** [comment]
![screenshot from 2017-05-09 17-47-35](https://cloud.githubusercontent.com/assets/13695616/25850363/a3ad84a0-34df-11e7-962d-183a52d3f7db.png)

Seriously guys, this project was developed under GDG-VIT organization. We even refused your proposal. Then also you merged it with your Enhancement Suite. At least you should have given proper credits to GDG-VIT even if you copied it without our approval. IMO Everybody should maintain proper ethics while working even though everything is open source nowadays. And yes, atleast learn to copy properly !

**Comment by shubham0704** [comment]
When you copy something next time be aware that you are under the scanner of a lot of developers. Copying feels downgrading also you didn't enhance it but made it worse look at those colors.Change those at least.

**Comment by rahulkapoor90** [comment]
@ujjwal96 @aalind0 Your MyVIT-Chrome is open-source and without any license makes it hard for the VES Team to give proper credits. You guys haven't added any proper license and without asking or contacting me have started the name & shame game. Yes, I am using your functionalities in VES but that is only for testing purpose and we do intend to remove in an upcoming release. Never we do something, without proper agreement or contacting the intended developers. 

PS: See it below as I told my team member that we are just testing it and that's why haven't pushed the code to master as well. Any other problems let me know. 
![chrome_2017-05-09_18-56-04](https://cloud.githubusercontent.com/assets/11207756/25853102/2b6f65da-34e9-11e7-833a-43855f697379.png)
